### PR TITLE
UU-116 - Provide facility to disable specific question types.

### PR DESCRIPTION
**Pull request by andrewhancox**
Fix for issue https://github.com/jhoopes/moodle-mod_activequiz/issues/19
Please let me know if you are unhappy with any part of this patch.
Thanks
Andrew

### CODE REVIEW

**Comment by jhoopes** [comment]
Hi Andrew,

Thanks for this, sorry that I've been slow getting back to you on this, apple really killed my development workflow with the disregard to customizations to my own php/apache settings, and because of that, I've moved to using vagrant and puphpet, and so that's taken me more time than I'd have liked to get straitened out.  

I wanted to test the code before making this comment, just in case you addressed it in some way I was missing, but, while I think it this is a great first step, the one thing it's missing is stopping a user from creating those disabled question types on the quiz edit page.  While it's true, that even if they create a disabled question, it won't show up in the list of questions to add to the quiz, the interface then becomes confusing because then the question they just created won't show up, and then the instructor may just not understand what's going on.

I've kind of wavered back and forth on what the "best" way of doing this would be, and we could theoretically just re-write/override, with tiny changes, the core question bank functionality in generating that question list, even then, part of me feels like that would overall be confusing to the instructor, because they can see all of the question types in the normal question bank view, which is what I'm pulling in as the interface for adding a question.

A slightly "better" approach, I've been thinking of was instead of fully removing the question from the list of questions, just remove the add-to-quiz button and grey out the text, with a description below outlining that greyed out questions are disabled questions for active quiz.  (with some kind of logic to only show that message if any question types were disabled)  That way the instructor can at least know their questions didn't "disappear".  

The other thing we'd need in either case is validation on the add question button press so that a user can't subvert the disabled question question type. 

What are your thoughts?

Thanks,

**Comment by andrewhancox** [comment]
I've found a way to do this neatly by overriding another function on the question bank view class. The commit has been added to this pull request.
Thanks
Andrew

**Comment by andrewhancox** [comment]
jhoopes - have you had a chance to look at my addition to this patch yet?

**Comment by jhoopes** [comment]
Hi Andrew,

My apologies for not getting back to you... I've been sick, as well as being incredibly busy with a house renovation, which has turned into a lot more.  I will definitely try to look at this over this coming weekend and get back to you...

I'm sorry I can't promise more than that right now, just got a lot going on,

John

**Comment by jhoopes** [comment]
My apologies again for this being so long int he running.  This looks good.  I still may end up adding a warning to the screen at another time for instructors that might be confused as to why they can see all questions in the main course question bank but not in the module, but that shouldn't block me adding this.  

Thanks for your work and patience for me taking too long on this.@Kathrin84

John

**Pull request merged**
